<Project Sdk="Godot.NET.Sdk/4.7.0">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup>
    <DefaultItemExcludes>$(DefaultItemExcludes);addons_src\**\*</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GDTask" Version="3.0.0" />
  </ItemGroup>

  <Import Project="addons\YarnSpinner-Godot\YarnSpinner-Godot.props" />
</Project>
